# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QR_HW11R6PLcxkY2-jUMTIKwbQF2YrTN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("heart.csv")
df.head()
df.info()
df.describe()
df.isnull().sum()
X = df.drop("target", axis=1)
y = df["target"]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
from sklearn.metrics import accuracy_score

pred = dt.predict(X_test)

print("Decision Tree Accuracy:",
      accuracy_score(y_test, pred))
from sklearn.tree import plot_tree

plt.figure(figsize=(20,10))

plot_tree(
dt,
filled=True,
            feature_names=X.columns
)
plt.show()